/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

'use strict';

import IRichLanguageConfiguration = monaco.languages.LanguageConfiguration;
import ILanguage = monaco.languages.IMonarchLanguage;

export var conf:IRichLanguageConfiguration = {
	comments: {
		lineComment: '*'
	},
	brackets: [['[',']'],['(',')']],
	autoClosingPairs: [
		{ open: '\'', close: '\'', notIn: ['string', 'comment'] },
		{ open: '[', close: ']', notIn: ['string', 'comment'] },
		{ open: '(', close: ')', notIn: ['string', 'comment'] },
		{ open: '{', close: '}', notIn: ['string', 'comment'] },
		{ open: '|', close: '|', notIn: ['string', 'comment'] },
		{ open: '`', close: '`', notIn: ['string', 'comment'] }
	]
	// enhancedBrackets:[
	// 	{ openTrigger: 'n', open: /begin$/i, closeComplete: 'end', matchCase: true },
	// 	{ openTrigger: 'e', open: /case$/i, closeComplete: 'end', matchCase: true },
	// 	{ openTrigger: 'n', open: /when$/i, closeComplete: 'then', matchCase: true }
	// ],
};

export var language = <ILanguage> {
	name: 'abap',

	defaultToken: '',
	tokenPostfix: '.abap',
	ignoreCase: true,

	brackets: [
		{ open: '[', close: ']', token: 'delimiter.square' },
		{ open: '(', close: ')', token: 'delimiter.parenthesis' }
	],

	keywords: [
		'ABAP-SOURCE',
		'ABBREVIATED',
		'ABS',
		'ABSTRACT',
		'ACCEPT',
		'ACCEPTING',
		'ACCORDING',
		'ACTIVATION',
		'ACTUAL',
		'ADD',
		'ADD-CORRESPONDING',
		'ADJACENT',
		'AFTER',
		'ALIAS',
		'ALIASES',
		'ALIGN',
		'ALL',
		'ALLOCATE',
		'ALPHA',
		'ANALYSIS',
		'ANALYZER',
		'AND',
		'ANY',
		'APPEND',
		'APPENDAGE',
		'APPENDING',
		'APPLICATION',
		'ARCHIVE',
		'AREA',
		'ARITHMETIC',
		'AS',
		'ASCENDING',
		'ASPECT',
		'ASSERT',
		'ASSIGN',
		'ASSIGNED',
		'ASSIGNING',
		'ASSOCIATION',
		'ASYNCHRONOUS',
		'AT',
		'ATTRIBUTES',
		'AUTHORITY',
		'AUTHORITY-CHECK',
		'AVG',
		'BACK',
		'BACKGROUND',
		'BACKUP',
		'BACKWARD',
		'BADI',
		'BASE',
		'BEFORE',
		'BEGIN',
		'BETWEEN',
		'BIG',
		'BINARY',
		'BINTOHEX',
		'BIT',
		'BIT-AND',
		'BIT-NOT',
		'BIT-OR',
		'BIT-XOR',
		'BLACK',
		'BLANK',
		'BLANKS',
		'BLOB',
		'BLOCK',
		'BLOCKS',
		'BLUE',
		'BOUND',
		'BOUNDARIES',
		'BOUNDS',
		'BOXED',
		'BREAK-POINT',
		'BT',
		'BUFFER',
		'BY',
		'BYPASSING',
		'BYTE',
		'BYTE-CA',
		'BYTE-CN',
		'BYTE-CO',
		'BYTE-CS',
		'BYTE-NA',
		'BYTE-NS',
		'BYTE-ORDER',
		'CA',
		'CALL',
		'CALLING',
		'CASE',
		'CAST',
		'CASTING',
		'CATCH',
		'CEIL',
		'CENTER',
		'CENTERED',
		'CHAIN',
		'CHAIN-INPUT',
		'CHAIN-REQUEST',
		'CHANGE',
		'CHANGING',
		'CHANNELS',
		'CHAR',
		'CHAR-TO-HEX',
		'CHARACTER',
		'CHECK',
		'CHECKBOX',
		'CI_',
		'CIRCULAR',
		'CLASS',
		'CLASS-CODING',
		'CLASS-DATA',
		'CLASS-EVENTS',
		'CLASS-METHODS',
		'CLASS-POOL',
		'CLEANUP',
		'CLEAR',
		'CLIENT',
		'CLNT',
		'CLOB',
		'CLOCK',
		'CLOSE',
		'CN',
		'CO',
		'COALESCE',
		'CODE',
		'CODING',
		'COL_BACKGROUND',
		'COL_GROUP',
		'COL_HEADING',
		'COL_KEY',
		'COL_NEGATIVE',
		'COL_NORMAL',
		'COL_POSITIVE',
		'COL_TOTAL',
		'COLLECT',
		'COLOR',
		'COLUMN',
		'COLUMNS',
		'COMMENT',
		'COMMENTS',
		'COMMIT',
		'COMMON',
		'COMMUNICATION',
		'COMPARING',
		'COMPONENT',
		'COMPONENTS',
		'COMPRESSION',
		'COMPUTE',
		'CONCAT',
		'CONCAT_WITH_SPACE',
		'CONCATENATE',
		'COND',
		'CONDENSE',
		'CONDITION',
		'CONNECT',
		'CONNECTION',
		'CONSTANTS',
		'CONTEXT',
		'CONTEXTS',
		'CONTINUE',
		'CONTROL',
		'CONTROLS',
		'CONV',
		'CONVERSION',
		'CONVERT',
		'COPIES',
		'COPY',
		'CORRESPONDING',
		'COUNT',
		'COUNTRY',
		'COVER',
		'CP',
		'CPI',
		'CREATE',
		'CREATING',
		'CRITICAL',
		'CS',
		'CUKY',
		'CURR',
		'CURRENCY',
		'CURRENCY_CONVERSION',
		'CURRENT',
		'CURSOR',
		'CURSOR-SELECTION',
		'CUSTOMER',
		'CUSTOMER-FUNCTION',
		'DANGEROUS',
		'DATA',
		'DATABASE',
		'DATAINFO',
		'DATASET',
		'DATE',
		'DATS',
		'DATS_ADD_DAYS',
		'DATS_ADD_MONTHS',
		'DATS_DAYS_BETWEEN',
		'DATS_IS_VALID',
		'DAYLIGHT',
		'DD/MM/YY',
		'DD/MM/YYYY',
		'DDMMYY',
		'DEALLOCATE',
		'DEC',
		'DECIMAL_SHIFT',
		'DECIMALS',
		'DECLARATIONS',
		'DEEP',
		'DEFAULT',
		'DEFERRED',
		'DEFINE',
		'DEFINING',
		'DEFINITION',
		'DELETE',
		'DELETING',
		'DEMAND',
		'DEPARTMENT',
		'DESCENDING',
		'DESCRIBE',
		'DESTINATION',
		'DETAIL',
		'DIALOG',
		'DIRECTORY',
		'DISCONNECT',
		'DISPLAY',
		'DISPLAY-MODE',
		'DISTANCE',
		'DISTINCT',
		'DIV',
		'DIVIDE',
		'DIVIDE-CORRESPONDING',
		'DIVISION',
		'DO',
		'DUMMY',
		'DUPLICATE',
		'DUPLICATES',
		'DURATION',
		'DURING',
		'DYNAMIC',
		'DYNPRO',
		'E',
		'EDIT',
		'EDITOR-CALL',
		'ELSE',
		'ELSEIF',
		'EMPTY',
		'ENABLED',
		'ENABLING',
		'ENCODING',
		'END',
		'END-ENHANCEMENT-SECTION',
		'END-LINES',
		'END-OF-DEFINITION',
		'END-OF-FILE',
		'END-OF-PAGE',
		'END-OF-SELECTION',
		'END-TEST-INJECTION',
		'END-TEST-SEAM',
		'ENDAT',
		'ENDCASE',
		'ENDCATCH',
		'ENDCHAIN',
		'ENDCLASS',
		'ENDDO',
		'ENDENHANCEMENT',
		'ENDEXEC',
		'ENDFORM',
		'ENDFUNCTION',
		'ENDIAN',
		'ENDIF',
		'ENDING',
		'ENDINTERFACE',
		'ENDLOOP',
		'ENDMETHOD',
		'ENDMODULE',
		'ENDON',
		'ENDPROVIDE',
		'ENDSELECT',
		'ENDTRY',
		'ENDWHILE',
		'ENDWITH',
		'ENGINEERING',
		'ENHANCEMENT',
		'ENHANCEMENT-POINT',
		'ENHANCEMENT-SECTION',
		'ENHANCEMENTS',
		'ENTRIES',
		'ENTRY',
		'ENVIRONMENT',
		'EQ',
		'EQUIV',
		'ERRORMESSAGE',
		'ERRORS',
		'ESCAPE',
		'ESCAPING',
		'EVENT',
		'EVENTS',
		'EXACT',
		'EXCEPT',
		'EXCEPTION',
		'EXCEPTION-TABLE',
		'EXCEPTIONS',
		'EXCLUDE',
		'EXCLUDING',
		'EXEC',
		'EXECUTE',
		'EXISTS',
		'EXIT',
		'EXIT-COMMAND',
		'EXPAND',
		'EXPANDING',
		'EXPIRATION',
		'EXPLICIT',
		'EXPONENT',
		'EXPORT',
		'EXPORTING',
		'EXTEND',
		'EXTENDED',
		'EXTENSION',
		'EXTRACT',
		'FAIL',
		'FETCH',
		'FIELD',
		'FIELD-GROUPS',
		'FIELD-SYMBOL',
		'FIELD-SYMBOLS',
		'FIELDS',
		'FILE',
		'FILTER',
		'FILTER-TABLE',
		'FILTERS',
		'FINAL',
		'FIND',
		'FIRST',
		'FIRST-LINE',
		'FIXED-POINT',
		'FKEQ',
		'FKGE',
		'FLOOR',
		'FLTP',
		'FLUSH',
		'FONT',
		'FOR',
		'FORM',
		'FORMAT',
		'FORWARD',
		'FOUND',
		'FRAME',
		'FRAMES',
		'FREE',
		'FRIENDS',
		'FROM',
		'FUNCTION',
		'FUNCTION-POOL',
		'FUNCTIONALITY',
		'FURTHER',
		'GAPS',
		'GE',
		'GENERATE',
		'GET',
		'GIVING',
		'GKEQ',
		'GKGE',
		'GLOBAL',
		'GRANT',
		'GREEN',
		'GROUP',
		'GROUPS',
		'GT',
		'HANDLE',
		'HANDLER',
		'HARMLESS',
		'HASHED',
		'HAVING',
		'HDB',
		'HEAD-LINES',
		'HEADER',
		'HEADERS',
		'HEADING',
		'HELP-ID',
		'HELP-REQUEST',
		'HEXTOBIN',
		'HIDE',
		'HIGH',
		'HINT',
		'HOLD',
		'HOTSPOT',
		'I',
		'ICON',
		'ID',
		'IDENTIFICATION',
		'IDENTIFIER',
		'IDS',
		'IF',
		'IGNORE',
		'IGNORING',
		'IMMEDIATELY',
		'IMPLEMENTATION',
		'IMPLEMENTATIONS',
		'IMPLEMENTED',
		'IMPLICIT',
		'IMPORT',
		'IMPORTING',
		'IN',
		'INACTIVE',
		'INCL',
		'INCLUDE',
		'INCLUDES',
		'INCLUDING',
		'INCREMENT',
		'INDEX',
		'INDEX-LINE',
		'INFOTYPES',
		'INHERITING',
		'INIT',
		'INITIAL',
		'INITIALIZATION',
		'INNER',
		'INOUT',
		'*-INPUT',
		'INPUT',
		'INSERT',
		'INSTANCE',
		'INSTANCES',
		'INSTR',
		'INT1',
		'INT2',
		'INT4',
		'INT8',
		'INTENSIFIED',
		'INTERFACE',
		'INTERFACE-POOL',
		'INTERFACES',
		'INTERNAL',
		'INTERVALS',
		'INTO',
		'INVERSE',
		'INVERTED-DATE',
		'IS',
		'ISO',
		'ITNO',
		'JOB',
		'JOIN',
		'KEEP',
		'KEEPING',
		'KERNEL',
		'KEY',
		'KEYS',
		'KEYWORDS',
		'KIND',
		'LANG',
		'LANGUAGE',
		'LAST',
		'LATE',
		'LAYOUT',
		'LE',
		'LEADING',
		'LEAVE',
		'LEFT',
		'LEFT-JUSTIFIED',
		'LEFTPLUS',
		'LEFTSPACE',
		'LEGACY',
		'LENGTH',
		'LET',
		'LEVEL',
		'LEVELS',
		'LIKE',
		'LINE',
		'LINE-COUNT',
		'LINE-SELECTION',
		'LINE-SIZE',
		'LINEFEED',
		'LINES',
		'LIST',
		'LIST-PROCESSING',
		'LISTBOX',
		'LITTLE',
		'LLANG',
		'LOAD',
		'LOAD-OF-PROGRAM',
		'LOB',
		'LOCAL',
		'LOCALE',
		'LOCATOR',
		'LOG-POINT',
		'LOGFILE',
		'LOGICAL',
		'LONG',
		'LOOP',
		'LOW',
		'LOWER',
		'LPAD',
		'LPI',
		'LT',
		'LTRIM',
		'M',
		'MAIL',
		'MAIN',
		'MAJOR-ID',
		'MAPPING',
		'MARGIN',
		'MARK',
		'MASK',
		'MATCH',
		'MATCHCODE',
		'MAX',
		'MAXIMUM',
		'MEDIUM',
		'MEMBERS',
		'MEMORY',
		'MESH',
		'MESSAGE',
		'MESSAGE-ID',
		'MESSAGES',
		'MESSAGING',
		'METHOD',
		'METHODS',
		'MIN',
		'MINIMUM',
		'MINOR-ID',
		'MM/DD/YY',
		'MM/DD/YYYY',
		'MMDDYY',
		'MOD',
		'MODE',
		'MODIF',
		'MODIFIER',
		'MODIFY',
		'MODULE',
		'MOVE',
		'MOVE-CORRESPONDING',
		'MULTIPLY',
		'MULTIPLY-CORRESPONDING',
		'NA',
		'NAME',
		'NAMETAB',
		'NATIVE',
		'NB',
		'NE',
		'NESTED',
		'NESTING',
		'NEW',
		'NEW-LINE',
		'NEW-PAGE',
		'NEW-SECTION',
		'NEXT',
		'NO',
		'NO-DISPLAY',
		'NO-EXTENSION',
		'NO-GAP',
		'NO-GAPS',
		'NO-GROUPING',
		'NO-HEADING',
		'NO-SCROLLING',
		'NO-SIGN',
		'NO-TITLE',
		'NO-TOPOFPAGE',
		'NO-ZERO',
		'NODE',
		'NODES',
		'NON-UNICODE',
		'NON-UNIQUE',
		'NOT',
		'NP',
		'NS',
		'NULL',
		'NUMBER',
		'NUMC',
		'O',
		'OBJECT',
		'OBJECTS',
		'OBLIGATORY',
		'OCCURRENCE',
		'OCCURRENCES',
		'OCCURS',
		'OF',
		'OFF',
		'OFFSET',
		'OLE',
		'ON',
		'ONLY',
		'OPEN',
		'OPTION',
		'OPTIONAL',
		'OPTIONS',
		'OR',
		'ORDER',
		'OTHER',
		'OTHERS',
		'OUT',
		'OUTER',
		'OUTPUT',
		'OUTPUT-LENGTH',
		'OVERFLOW',
		'OVERLAY',
		'PACK',
		'PACKAGE',
		'PAD',
		'PADDING',
		'PAGE',
		'PAGES',
		'PARAMETER',
		'PARAMETER-TABLE',
		'PARAMETERS',
		'PART',
		'PARTIALLY',
		'PATTERN',
		'PERCENTAGE',
		'PERFORM',
		'PERFORMING',
		'PERSON',
		'PF',
		'PF-STATUS',
		'PINK',
		'PLACES',
		'POOL',
		'POS_HIGH',
		'POS_LOW',
		'POSITION',
		'PRAGMAS',
		'PRECOMPILED',
		'PREFERRED',
		'PRESERVING',
		'PRIMARY',
		'PRINT',
		'PRINT-CONTROL',
		'PRIORITY',
		'PRIVATE',
		'PROCEDURE',
		'PROCESS',
		'PROGRAM',
		'PROPERTY',
		'PROTECTED',
		'PROVIDE',
		'PUBLIC',
		'PUSH',
		'PUSHBUTTON',
		'PUT',
		'QUAN',
		'QUEUE-ONLY',
		'QUICKINFO',
		'RADIOBUTTON',
		'RAISE',
		'RAISING',
		'RANGE',
		'RANGES',
		'RAW',
		'READ',
		'READ-ONLY',
		'READER',
		'RECEIVE',
		'RECEIVED',
		'RECEIVER',
		'RECEIVING',
		'RED',
		'REDEFINITION',
		'REDUCE',
		'REDUCED',
		'REF',
		'REFERENCE',
		'REFRESH',
		'REGEX',
		'REJECT',
		'REMOTE',
		'RENAMING',
		'REPLACE',
		'REPLACEMENT',
		'REPLACING',
		'REPORT',
		'REQUEST',
		'REQUESTED',
		'RESERVE',
		'RESET',
		'RESOLUTION',
		'RESPECTING',
		'RESPONSIBLE',
		'RESULT',
		'RESULTS',
		'RESUMABLE',
		'RESUME',
		'RETRY',
		'RETURN',
		'RETURNCODE',
		'RETURNING',
		'RETURNS',
		'RIGHT',
		'RIGHT-JUSTIFIED',
		'RIGHTPLUS',
		'RIGHTSPACE',
		'RISK',
		'RMC_COMMUNICATION_FAILURE',
		'RMC_INVALID_STATUS',
		'RMC_SYSTEM_FAILURE',
		'ROLE',
		'ROLLBACK',
		'ROUND',
		'ROWS',
		'RPAD',
		'RTRIM',
		'RUN',
		'SAP',
		'SAP-SPOOL',
		'SAVING',
		'SCALE_PRESERVING',
		'SCALE_PRESERVING_SCIENTIFIC',
		'SCAN',
		'SCIENTIFIC',
		'SCIENTIFIC_WITH_LEADING_ZERO',
		'SCREEN',
		'SCROLL',
		'SCROLL-BOUNDARY',
		'SCROLLING',
		'SEARCH',
		'SECONDARY',
		'SECONDS',
		'SECTION',
		'SELECT',
		'SELECT-OPTIONS',
		'SELECTION',
		'SELECTION-SCREEN',
		'SELECTION-SET',
		'SELECTION-SETS',
		'SELECTION-TABLE',
		'SELECTIONS',
		'SEND',
		'SEPARATE',
		'SEPARATED',
		'SET',
		'SHARED',
		'SHIFT',
		'SHORT',
		'SHORTDUMP-ID',
		'SIGN',
		'SIGN_AS_POSTFIX',
		'SIMPLE',
		'SINGLE',
		'SIZE',
		'SKIP',
		'SKIPPING',
		'SMART',
		'SOME',
		'SORT',
		'SORTABLE',
		'SORTED',
		'SOURCE',
		'SPACE',
		'SPECIFIED',
		'SPLIT',
		'SPOOL',
		'SPOTS',
		'SQL',
		'SQLSCRIPT',
		'SSTRING',
		'STABLE',
		'STAMP',
		'STANDARD',
		'START-OF-SELECTION',
		'STARTING',
		'STATE',
		'STATEMENT',
		'STATEMENTS',
		'STATIC',
		'STATICS',
		'STATUSINFO',
		'STEP-LOOP',
		'STOP',
		'STRUCTURE',
		'STRUCTURES',
		'STYLE',
		'SUBKEY',
		'SUBMATCHES',
		'SUBMIT',
		'SUBROUTINE',
		'SUBSCREEN',
		'SUBSTRING',
		'SUBTRACT',
		'SUBTRACT-CORRESPONDING',
		'SUFFIX',
		'SUM',
		'SUMMARY',
		'SUMMING',
		'SUPPLIED',
		'SUPPLY',
		'SUPPRESS',
		'SWITCH',
		'SWITCHSTATES',
		'SYMBOL',
		'SYNCPOINTS',
		'SYNTAX',
		'SYNTAX-CHECK',
		'SYNTAX-TRACE',
		'SYSTEM-CALL',
		'SYSTEM-EXCEPTIONS',
		'SYSTEM-EXIT',
		'TAB',
		'TABBED',
		'TABLE',
		'TABLES',
		'TABLEVIEW',
		'TABSTRIP',
		'TARGET',
		'TASK',
		'TASKS',
		'TEST',
		'TEST-INJECTION',
		'TEST-SEAM',
		'TESTING',
		'TEXT',
		'TEXTPOOL',
		'THEN',
		'THROW',
		'TIME',
		'TIMES',
		'TIMESTAMP',
		'TIMEZONE',
		'TIMS',
		'TIMS_IS_VALID',
		'TITLE',
		'TITLE-LINES',
		'TITLEBAR',
		'?TO',
		'TO',
		'TOKENIZATION',
		'TOKENS',
		'TOP-LINES',
		'TOP-OF-PAGE',
		'TRACE-FILE',
		'TRACE-TABLE',
		'TRAILING',
		'TRANSACTION',
		'TRANSFER',
		'TRANSFORMATION',
		'TRANSLATE',
		'TRANSPORTING',
		'TRMAC',
		'TRUNCATE',
		'TRUNCATION',
		'TRY',
		'TSTMP_ADD_SECONDS',
		'TSTMP_CURRENT_UTCTIMESTAMP',
		'TSTMP_IS_VALID',
		'TSTMP_SECONDS_BETWEEN',
		'TYPE',
		'TYPE-POOL',
		'TYPE-POOLS',
		'TYPES',
		'ULINE',
		'UNASSIGN',
		'UNDER',
		'UNICODE',
		'UNION',
		'UNIQUE',
		'UNIT',
		'UNIT_CONVERSION',
		'UNIX',
		'UNPACK',
		'UNTIL',
		'UNWIND',
		'UP',
		'UPDATE',
		'UPPER',
		'USER',
		'USER-COMMAND',
		'USING',
		'UTF-8',
		'VALID',
		'VALUE',
		'VALUE-REQUEST',
		'VALUES',
		'VARY',
		'VARYING',
		'VERIFICATION-MESSAGE',
		'VERSION',
		'VIA',
		'VIEW',
		'VISIBLE',
		'WAIT',
		'WARNING',
		'WHEN',
		'WHENEVER',
		'WHERE',
		'WHILE',
		'WIDTH',
		'WINDOW',
		'WINDOWS',
		'WITH',
		'WITH-HEADING',
		'WITH-TITLE',
		'WITHOUT',
		'WORD',
		'WORK',
		'WRITE',
		'WRITER',
		'XML',
		'XSD',
		'YELLOW',
		'YES',
		'YYMMDD',
		'Z',
		'ZERO',
		'ZONE',
		'1',
		'2',
		'3',
		'4',
		'5',
		'6',
		'7'
	],
	operators: [
		// Logical
		'is','not','or','and',
		// comparison
		'<','>','<=','>=','<>','eq','ne','lt','le','gt','ge','cs',
		// Predicates
		'CONTAINS','FREETEXT','IS','NULL',
		// Pivoting
		'PIVOT','UNPIVOT',
		// Other
		'&&', '='
	],
	builtinTypes: [
		//Numeric
		'b','s','i','int8','p','decfloat16','decfloat34','f',
		//Character type
		'c','n','string',
		//Byte-like
		'x','xstring',
		//Date types
		'd','t',
		//Generic types
		'any','any table','c','clike','csequence','data','decfloat','hashed table','index table','n','numeric','object','p','simple','sorted table','standard table',
		'table','x','xsequence'
	],
	builtinFunctions: [
		//Logical
		'boolc', 'boolx', 'xsdbool','contains','contains_any_of','contains_any_not_of','matches','line_exists',
		//Numeric
		'abs','ceil','floor','frac','sign','trunc','ipow','nmax','nmin','acos','asin','atan','cos','sin','tan','cosh','sinh','tanh','exp','log','log10','sqrt','round','rescale',
		//String
		'charlen','dbmaxlen','numofchar','strlen','char_off','cmax','cmin','count','count_any_of','count_any_not_of','distance','condense','concat_lines_of','escape','find','find_end',
		'find_any_not_of','insert','match','repeat','replace','reverse','Segment','shift_left','shift_right','substring','substring_after','substring_from','substring_before','substring_to',
		'to_upper','to_lower','to_mixed','from_mixed','translate',
		//Byte String
		'xstrlen','bit-set',
		//Table
		'lines','line_index'
	],
	pseudoColumns: [
		'$ACTION', '$IDENTITY', '$ROWGUID', '$PARTITION'
	],
	tokenizer: {
		root: [
			{ include: '@comments' },
			{ include: '@whitespace' },
			{ include: '@pseudoColumns' },
			{ include: '@numbers' },
			{ include: '@strings' },
			{ include: '@complexIdentifiers' },
			{ include: '@scopes' },
			[/[\.]/, 'delimiter'],
			[/[()]/, '@brackets'],
			{ include: '@mainIdentifiers'}
			{ include: '@operator'}
		],

		mainIdentifiers: [
			[/([\w@#$]\-[\w@#$]|[\w@#$])+/ig, { cases: {
							'@keywords': 'keyword',
							'@operators': 'operator',
							'@builtinTypes': 'predefined',
							'@builtinFunctions': 'predefined',
							'@default': 'identifier' }
						}],
		],

		operator: [
			[/(\*{2})|([\+\-\*\/\%\=])/, 'operator'],
		],

		whitespace: [
			[/\s+/, 'white']
		],
		comments: [
			[/^\*.*\n?/, 'comment'],
			[/".*\n?/, 'comment.partial'],
			[/\#\#.*\n?/,'comment.exceptions']
		],

		pseudoColumns: [
			[/[$][A-Za-z_][\w@#$]*/, { cases: {
				'@pseudoColumns': 'predefined',
				'@default': 'identifier'
			}}],
		],
		numbers: [
			[/0[xX][0-9a-fA-F]*/, 'number'],
			[/[$][+-]*\d*(\.\d*)?/, 'number'],
			[/((\d+(\.\d*)?)|(\.\d+))([eE][\-+]?\d+)?/, 'number']
		],
		strings: [
			[/N'/, { token: 'string', next: '@string' }],
			[/'/, { token: 'string', next: '@string' }],
			[/`/, { token: 'string', next: '@stringBacktick' }],
			[/\|/, { token: 'string', next: '@stringPipe' }]
		],
		string: [
			[/[^']+/, 'string'],
			[/'/, { token: 'string', next: '@pop' }]
		],
		stringBacktick: [
			[/[^`]+/, 'string'],
			[/`/, { token: 'string', next: '@pop' }]
		],
		stringPipe: [
			[/\{/, { token: 'operator', next: '@interpolatedexpression' }],
			[/\|/, { token: 'string', next: '@pop' }],
			[/./, { token: 'string' }]
		],
		interpolatedexpression: [
			[ /\{/, { token: 'operator', next: '@interpolatedexpression' }],
			[ /\}/, { token: 'operator', next: '@pop' } ],
			{ include: '@whitespace' },
			{ include: '@pseudoColumns' },
			{ include: '@numbers' },
			{ include: '@strings' },
			{ include: '@complexIdentifiers' },
			{ include: '@scopes' },
			{ include: '@mainIdentifiers'},
			{ include : '@operator'}
		],
		complexIdentifiers: [
			[/\[/, { token: 'identifier.quote', next: '@bracketedIdentifier' }],
			[/'/, { token: 'identifier.quote', next: '@quotedIdentifier' }]
		],
		bracketedIdentifier: [
			[/[^\]]+/, 'identifier'],
			[/]]/, 'identifier'],
			[/]/, { token: 'identifier.quote', next: '@pop' }]
		],
		quotedIdentifier: [
			[/[^']+/, 'identifier'],
			[/''/, 'identifier'],
			[/'/, { token: 'identifier.quote', next: '@pop' }]
		],
		scopes: [
			[/(i)^\s*(class|method|form)\s+(?=[a-z_][a-z_0-9])/gi, 'keyword.block']

			// [/BEGIN\s+(DISTRIBUTED\s+)?TRAN(SACTION)?\b/i, 'keyword'],
			// [/BEGIN\s+TRY\b/i, { token: 'keyword.try' }],
			// [/END\s+TRY\b/i, { token: 'keyword.try' }],
			// [/BEGIN\s+CATCH\b/i, { token: 'keyword.catch' }],
			// [/END\s+CATCH\b/i, { token: 'keyword.catch' }],
			// [/(BEGIN|CASE)\b/i, { token: 'keyword.block' }],
			// [/END\b/i, { token: 'keyword.block' }],
			// [/WHEN\b/i, { token: 'keyword.choice' }],
			// [/THEN\b/i, { token: 'keyword.choice' }]
		]
	}
};
